### ISSUE TITLE
Addons installing to "nullInterface"

### ISSUE THREAD

**Issue by trey-k** [erikabp123/ClassicAddonManager#25]
When attempting to install or update addons they do not end up in Classic's selected directory, I suspect it may have to do with multiple drive locations.

During setup I manually selected my Classic install on a separate hard drive (ClassicAddonManager reports "**E**:\Battle.net\World of Warcraft\_classic_\Interface\AddOns\"), after updating you can find the addons in a "nullInterface" folder where you ran the .jar file ("**D**:\Downloads\") and you can see the nullInterface directory set in managed.json

Windows 10, OpenJDK 15

**Comment by erikabp123** [comment]
Thank you for reporting this. I believe it is related to having the manager in a different drive than your wow installation as you state!

**Comment by erikabp123** [comment]
Fixed in new version

**Comment by trey-k** [comment]
Downloaded new release and deleted all previous files, am still experiencing the same problem, can still see nullInterface set in the managed.json and the downloaded files in the working directory

**Comment by erikabp123** [comment]
Okay, can you do the following for me? Will help me trouble shoot. Let me know if you need help with any of the commands:

1.  Open CMD and navigate to the Drive that you have the manager installed on
2.  Navigate to the root of the Drive
3.  Run the following command: dir /s /b "WoW.exe" (you might need to change WoW.exe to wow.exe or WOW.exe, as I cant remember if it is upper or lowercase. Likewise, if it's classic you have installed the name of the exe is different, so change the text to the appropriate value)
4.  Post a screenshot of the results here

I suspect I know what's going wrong, but am unable to replicate the issue on my home pc.

**Comment by trey-k** [comment]
Drive setup is the same as original post, manager running in it's folder in D:\Downloads\ with the game located elsewhere on E:\\, captured results for both:

![image](https://user-images.githubusercontent.com/10183408/103033203-cd3f3200-4516-11eb-935c-f85a538a4ed3.png)

**Comment by erikabp123** [comment]
I suspect it may be reading the line File not found" as a successful search result, and when it attempts to validate the exe location I am getting a null pointer exception which causes the issue. I can do a simple check for the contents of the search result and filter out any that don't resemble a directory. I however do not have access to my windows pc until the 29th, so I can't test the solution until then.

**Comment by erikabp123** [comment]
On closer inspection, it seems I already implemented a solution that should filter out the File not found type responses. Running the program through a virtual machine with windows 10 I cannot replicate the null exception. If you are able to record a video showing exactly how you set it up with all the steps and showing the relevant files with the null/interface result that would maybe be helpful. It could be that there is something I am not understanding or at the very least it will help me to know exactly where to look for the source of the bug.

**Comment by erikabp123** [comment]
Would you be able to record a video of the exact steps you take which causes this issue? including showing the relevant files during the video. Would help me identify where to begin looking. It seems the above comment is NOT the cause of the problem, in so far as I can tell. Would you also be able to open your WowClassic.exe properties and show file version etc?

**Comment by erikabp123** [comment]
Was able to replicate the issue, it was specifically related to manual install location selection, the location object was not being properly updated and would therefore have a null value. Fixed in newest version
